// This unit is autogenerated. Do not edit it manually.
// Source: JSON pasted from clipboard
// Date: 7/16/2024 4:58:20 PM

unit BundleJsonObject;

interface

uses
  System.Classes, System.JSON.Serializers;

type
  [JsonSerialize(TJsonMemberSerialization.Public)]
  TUrl = class(TPersistent)
  private
    Fweb: string;
    Fbittorrent: string;
  public
    property web: string read Fweb write Fweb;
    property bittorrent: string read Fbittorrent write Fbittorrent;
  end;

  [JsonSerialize(TJsonMemberSerialization.Public)]
  TDownload_struct = class(TPersistent)
  private
    Fsha1: string;
    Fname: string;
    Furl: TUrl;
    Fhuman_size: string;
    Ffile_size: Integer;
    Fsmall: Integer;
    Fmd5: string;
  public
    constructor Create;
    destructor Destroy; override;
    property sha1: string read Fsha1 write Fsha1;
    property name: string read Fname write Fname;
    property url: TUrl read Furl;
    property human_size: string read Fhuman_size write Fhuman_size;
    property file_size: Integer read Ffile_size write Ffile_size;
    property small: Integer read Fsmall write Fsmall;
    property md5: string read Fmd5 write Fmd5;
  end;

  [JsonSerialize(TJsonMemberSerialization.Public)]
  TOptions_dict = class(TPersistent)
  end;

  [JsonSerialize(TJsonMemberSerialization.Public)]
  TEmpty_tpkds = class(TPersistent)
  end;

  [JsonSerialize(TJsonMemberSerialization.Public)]
  TDownload = class(TPersistent)
  private
    Fdesktop_app_only: Boolean;
    Fmachine_name: string;
    Fdownload_struct: TArray<TDownload_struct>;
    Foptions_dict: TOptions_dict;
    Fdownload_identifier: string;
    Fplatform: string;
    Fdownload_version_number: string;
  public
    constructor Create;
    destructor Destroy; override;
    property desktop_app_only: Boolean read Fdesktop_app_only write Fdesktop_app_only;
    property machine_name: string read Fmachine_name write Fmachine_name;
    property download_struct: TArray<TDownload_struct> read Fdownload_struct write Fdownload_struct;
    property options_dict: TOptions_dict read Foptions_dict;
    property download_identifier: string read Fdownload_identifier write Fdownload_identifier;
    property platform: string read Fplatform write Fplatform;
    property download_version_number: string read Fdownload_version_number write Fdownload_version_number;
  end;

  [JsonSerialize(TJsonMemberSerialization.Public)]
  TPayee = class(TPersistent)
  private
    Fhuman_name: string;
    Fmachine_name: string;
  public
    property human_name: string read Fhuman_name write Fhuman_name;
    property machine_name: string read Fmachine_name write Fmachine_name;
  end;

  [JsonSerialize(TJsonMemberSerialization.Public)]
  TProduct = class(TPersistent)
  private
    Fcategory: string;
    Fmachine_name: string;
    Fempty_tpkds: TEmpty_tpkds;
    Fpost_purchase_text: string;
    Fhuman_name: string;
    Fpartial_gift_enabled: Boolean;
  public
    constructor Create;
    destructor Destroy; override;
    property category: string read Fcategory write Fcategory;
    property machine_name: string read Fmachine_name write Fmachine_name;
    property empty_tpkds: TEmpty_tpkds read Fempty_tpkds;
    property post_purchase_text: string read Fpost_purchase_text write Fpost_purchase_text;
    property human_name: string read Fhuman_name write Fhuman_name;
    property partial_gift_enabled: Boolean read Fpartial_gift_enabled write Fpartial_gift_enabled;
  end;

  [JsonSerialize(TJsonMemberSerialization.Public)]
  TSubproduct = class(TPersistent)
  private
    Fmachine_name: string;
    Furl: string;
    Fdownloads: TArray<TDownload>;
    Flibrary_family_name: string;
    Fpayee: TPayee;
    Fhuman_name: string;
    Fcustom_download_page_box_css: string;
    Fcustom_download_page_box_html: string;
    Ficon: string;
  public
    constructor Create;
    destructor Destroy; override;
    property machine_name: string read Fmachine_name write Fmachine_name;
    property url: string read Furl write Furl;
    property downloads: TArray<TDownload> read Fdownloads write Fdownloads;
    property library_family_name: string read Flibrary_family_name write Flibrary_family_name;
    property payee: TPayee read Fpayee;
    property human_name: string read Fhuman_name write Fhuman_name;
    property custom_download_page_box_css: string read Fcustom_download_page_box_css write Fcustom_download_page_box_css;
    property custom_download_page_box_html: string read Fcustom_download_page_box_html write Fcustom_download_page_box_html;
    property icon: string read Ficon write Ficon;
  end;

  [JsonSerialize(TJsonMemberSerialization.Public)]
  TBundle = class(TPersistent)
  private
    Famount_spent: Integer;
    Fproduct: TProduct;
    Fgamekey: string;
    Fuid: string;
    Fcreated: TDateTime;
    Fmissed_credit: string;
    Fsubproducts: TArray<TSubproduct>;
    Ftotal_choices: Integer;
    Fchoices_remaining: Integer;
    Fcurrency: string;
    Fis_giftee: Boolean;
    Fclaimed: Boolean;
    Ftotal: Integer;
    Fpath_ids: TArray<Int64>;
  public
    constructor Create;
    destructor Destroy; override;
    property amount_spent: Integer read Famount_spent write Famount_spent;
    property product: TProduct read Fproduct;
    property gamekey: string read Fgamekey write Fgamekey;
    property uid: string read Fuid write Fuid;
    property created: TDateTime read Fcreated write Fcreated;
    property missed_credit: string read Fmissed_credit write Fmissed_credit;
    property subproducts: TArray<TSubproduct> read Fsubproducts write Fsubproducts;
    property total_choices: Integer read Ftotal_choices write Ftotal_choices;
    property choices_remaining: Integer read Fchoices_remaining write Fchoices_remaining;
    property currency: string read Fcurrency write Fcurrency;
    property is_giftee: Boolean read Fis_giftee write Fis_giftee;
    property claimed: Boolean read Fclaimed write Fclaimed;
    property total: Integer read Ftotal write Ftotal;
    property path_ids: TArray<Int64> read Fpath_ids write Fpath_ids;
  end;

implementation

uses
  System.SysUtils, System.Generics.Collections;

constructor TDownload_struct.Create;
begin
  inherited Create;
  Furl := TUrl.Create;
end;

destructor TDownload_struct.Destroy;
begin
  FreeAndNil(Furl);
  inherited Destroy;
end;

constructor TDownload.Create;
begin
  inherited Create;
  Foptions_dict := TOptions_dict.Create;
end;

destructor TDownload.Destroy;
begin
  TArray.FreeValues<TDownload_struct>(Fdownload_struct);
  FreeAndNil(Foptions_dict);
  inherited Destroy;
end;

constructor TProduct.Create;
begin
  inherited Create;
  Fempty_tpkds := TEmpty_tpkds.Create;
end;

destructor TProduct.Destroy;
begin
  FreeAndNil(Fempty_tpkds);
  inherited Destroy;
end;

constructor TSubproduct.Create;
begin
  inherited Create;
  Fpayee := TPayee.Create;
end;

destructor TSubproduct.Destroy;
begin
  TArray.FreeValues<TDownload>(Fdownloads);
  FreeAndNil(Fpayee);
  inherited Destroy;
end;

constructor TBundle.Create;
begin
  inherited Create;
  Fproduct := TProduct.Create;
end;

destructor TBundle.Destroy;
begin
  FreeAndNil(Fproduct);
  TArray.FreeValues<TSubproduct>(Fsubproducts);
  TArray.FreeValues<Int64>(Fpath_ids);
  inherited Destroy;
end;

initialization

  RegisterClass(TUrl);
  RegisterClass(TDownload_struct);
  RegisterClass(TOptions_dict);
  RegisterClass(TEmpty_tpkds);
  RegisterClass(TDownload);
  RegisterClass(TPayee);
  RegisterClass(TProduct);
  RegisterClass(TSubproduct);
  RegisterClass(TBundle);

end.
